version: '3'

services:
  docker-mysql:
    image: mysql
    container_name: database-cpp
    environment:
      - MYSQL_ROOT_PASSWORD=00000000
      - MYSQL_DATABASE=dbi454066
      - MYSQL_PASSWORD=00000000
    ports:
      - "3306:3306"

  app:
    image: backend-cpp
    container_name: backend-cpp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://studmysql01.fhict.local/dbi454066
      SPRING_DATASOURCE_USERNAME: "dbi454066"
      SPRING_DATASOURCE_PASSWORD: "L-khb}_2EVng+*SG"
    build:
      dockerfile: "./backend/cpp/Dockerfile"

    depends_on:
      - docker-mysql

  frontend:
    image: frontend-cpp
    container_name: frontend-cpp
    ports:
      - "3000:3000"

  postgres:
          image: postgres:9.6
          environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
          logging:
            options:
              max-size: 10m
              max-file: "3"

  webserver:
          build: ./pipeline/dockerfiles
          restart: always
          depends_on:
            - postgres
          environment:
            - LOAD_EX=n
            - EXECUTOR=Local
          logging:
            options:
              max-size: 10m
              max-file: "3"
          volumes:
                - ./pipeline/dags:/usr/local/airflow/dags
                - ./pipeline/ip_files:/usr/local/airflow/ip_files
                - ./pipeline/op_files:/usr/local/airflow/op_files
          ports:
            - "8081:8080"
          command: webserver

          healthcheck:
            test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3